### ISSUE TITLE
Fehler JSON-Prozessor

### ISSUE THREAD

**Issue by Angelo131095** [klenzel/check_unifi65#1]
ich bekomme bei allen Checks den folgenden Fehler in icingaweb2 angezeigt:

"Bitte den JSON-Prozessor  installieren"

wie kann man dan Problem lösen?
Unifi-Controller Version: 6.5.55

**Comment by klenzel** [comment]
Siehe Readme, Installation, Punkt 1:
apt-get install jq curl
